node('openshift-totaljs-mongodb') {
  stage 'build'
  openshiftBuild(buildConfig: 'openshift-totaljs-mongodb', showBuildLogs: 'true')
  stage 'deploy'
  openshiftDeploy(deploymentConfig: 'openshift-totaljs-mongodb')
}
